blank_issues_enabled: true
contact_links:
  - name: Dragon Scrolls Project Page
    url: https://github.com/afyoung3083/dragon-scrolls-character-generator
    about: View the main Dragon Scrolls repository.
